# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/hdmiAxi/hdmiAxi/hdmiAxi.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_1/hdmi_clk_wiz_0_1.xci
# IP: The module: 'hdmi_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/hdmiAxi/hdmiAxi/hdmiAxi.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_1/hdmi_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/hdmiAxi/hdmiAxi/hdmiAxi.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_1/hdmi_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/hdmiAxi/hdmiAxi/hdmiAxi.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_1/hdmi_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/hdmiAxi/hdmiAxi/hdmiAxi.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_1/hdmi_clk_wiz_0_1.xci
# IP: The module: 'hdmi_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/hdmiAxi/hdmiAxi/hdmiAxi.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_1/hdmi_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/hdmiAxi/hdmiAxi/hdmiAxi.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_1/hdmi_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/hdmiAxi/hdmiAxi/hdmiAxi.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_1/hdmi_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
