# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/digilent-xdc-master/Nexys-Video-Master.xdc

# Block Designs: bd/hdmi/hdmi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi || ORIG_REF_NAME==hdmi} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_clk_wiz_0_1/hdmi_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_clk_wiz_0_1 || ORIG_REF_NAME==hdmi_clk_wiz_0_1} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_tc_0_0 || ORIG_REF_NAME==hdmi_v_tc_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_rgb2dvi_1_0/hdmi_rgb2dvi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_rgb2dvi_1_0 || ORIG_REF_NAME==hdmi_rgb2dvi_1_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_proc_sys_reset_0_0/hdmi_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_xlconstant_0_0/hdmi_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_xlconstant_0_0 || ORIG_REF_NAME==hdmi_xlconstant_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_dataGen_0_0/hdmi_dataGen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_dataGen_0_0 || ORIG_REF_NAME==hdmi_dataGen_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_util_vector_logic_0_0/hdmi_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_util_vector_logic_0_0 || ORIG_REF_NAME==hdmi_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/hdmi/hdmi_ooc.xdc
